name: Encrypt AES Key with RSA

on:
  push:
    branches:
      - main
  workflow_dispatch: # 支持手动触发

jobs:
  encrypt-aes-key:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cryptography

      - name: Encrypt AES Key
        env:
          ENCRYPTION_PASSWORD: ${{ secrets.ENCRYPTION_PASSWORD }}
        run: |
          python <<EOF
          import subprocess
          subprocess.run(['python', 'encrypt_aes_key.py'])
          EOF

      - name: Commit and Push Encrypted Keys
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add users_enc_aes_key.json
          git commit -m "Add encrypted AES keys [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
